# Generated by Django 6.0 on 2025-12-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=40)),
                ("street_number", models.CharField(max_length=10)),
                ("city_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNSET", "Unset"),
                        ],
                        default="UNSET",
                        max_length=10,
                    ),
                ),
                ("customer_id", models.UUIDField()),
                ("phone_number", models.CharField(max_length=15)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("birthday", models.DateField()),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="people.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField()),
                (
                    "appuser_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.appuser"
                    ),
                ),
            ],
        ),
    ]
