# Generated by Django 6.0 on 2026-01-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.RenameField(
            model_name="appuser",
            old_name="address_id",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="customerrelationship",
            old_name="appuser_id",
            new_name="appuser",
        ),
    ]
